version: "3.9"
services:
  postgres:
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: cisco
      POSTGRES_USER: cisco
    image: postgres
    restart: always
    
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    restart: alway
    ports: 
    - 4822/tcp
    links:
      - "postgres"

  guacamole:
    container_name: guacmole_compose
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: cisco
      POSTGRES_USER: cisco
    image: guacamole/guacamole
    links:
    - guacd
    ports:
    - 8080/tcp
    restart: always
